#I. falsche Tabelle 
create Assertion keinHausInSee CHECK(
	not exist(
		select * from See2 s,Haus h where ST_Crosses(s.umriss,h.umriss)
	));
#II. falsches not exiata
create Assertion keineStrasseDurchSpielplatz CHECK(
	not2 exist(
		select * from Strasse t, Spielplatz p where ST_Crosses(t.path,p.umriss)
));

#VI. falsche Spalte
create Assertion brueckeMussKreuzen CHECK(
	not exist(
	select b.id2 from bruecke as b where b.id not in (
		select b.id from bruecke as b, strasse s 
				where ST_Crosses(b.path2,s.path)
		union
		select b.id from bruecke as b, strassenbahn sb 
				where ST_Crosses(b.path, sb.path)
		union
		select b.id from bruecke as b, eisenbahn e 
				where ST_Crosses(b.path, e.path)
		union
		select b.id from bruecke as b, fluss f 
				where ST_Crosses(b.path, f.path)
)));

#VII. Klammer fehlt 
#//Es wird davon ausgegangen, dass eine Ampel immer an einer Straße ist
create Assertion AmpelAnWeg CHECK(
	not exist(
	select a.id from ampel as a where a.id not in (
		select a.id from ampel as a, strasse s 
				where ST_CoveredBy(a.pos,s.path)
		union
		select a.id from ampel as a, strassenbahn sb 
				where ST_CoveredBy(a.pos, sb.path)
		union
		select a.id from ampel as a, eisenbahn e 
				where ST_CoveredBy(a.pos, e.path)
));


#X. Parkplatz an Straße - doppelte assertion
create Assertion ParkplatzAnStraße Check(
	not exist(
	select a.id from Parkplatz as a where a.id not in (
		select a.id from Parkplatz as a, Strasse as b 
				where ST_Crosses(a.umriss,b.path))
));
