# falscher Bezeichner
create Assertions 1234 CHECK ( 
not exists (select * 
from See s, Haus h
where h.umriss <@ s.umriss));

# falscher Operator 
create Assertion keineStrassedurchHaus CHECK (
not exists ( select * 
from Haus h, Strasse s
where path(h.umriss) ?+ s.path));

# Schluesselwort als Bezeichner
create Assertion select CHECK ( 
not exists (select * 
from See s, Haus h
where h.umriss <@ s.umriss));

# Ungueltiges Praedikat
create Assertion keineStrassedurchHaus CHECK (
create Test (Field INTEGER));

# fehlendes Semikolon
create Assertion keineStrassedurchSpielplatz CHECK (
not exists (select *
from Strasse s, Spielplatz p
where s.path ?# p.umriss))





